# Generated by Django 2.2.6 on 2020-11-23 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=6)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='budget_tracker.Expense')),
                ('Electricity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Water', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Rent', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            bases=('budget_tracker.expense',),
        ),
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='budget_tracker.Expense')),
                ('Movies', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Shopping', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Special_Occasions', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            bases=('budget_tracker.expense',),
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='budget_tracker.Expense')),
                ('Junk', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Grocery', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
            bases=('budget_tracker.expense',),
        ),
        migrations.CreateModel(
            name='Misc',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='budget_tracker.Expense')),
                ('Medical', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Unlabelled', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            bases=('budget_tracker.expense',),
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='budget_tracker.Expense')),
                ('Local', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Work', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Trips', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            bases=('budget_tracker.expense',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='budget_tracker.User')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_tracker.User', to_field='username'),
        ),
    ]
