# Generated by Django 2.2.6 on 2020-11-18 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_tracker', '0004_auto_20200524_1725'),
    ]

    operations = [
        migrations.DeleteModel(
            name='account',
        ),
    ]
