# Generated by Django 2.2.6 on 2020-11-23 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_tracker', '0006_auto_20201123_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='type',
            new_name='asset',
        ),
        migrations.RenameField(
            model_name='liability',
            old_name='type',
            new_name='liability',
        ),
    ]
